apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  nodejs
  name: nodejs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: eyala/nodejs-hello:BUILD_NUMBER
        name: nodejs    
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
 selector:
    app:  nodejs
 ports:
  - name: http
    port: 8081
    protocol: TCP
 type: LoadBalancer
